# Generated by Django 5.0.4 on 2025-02-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='commune',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='quarter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
