# Generated by Django 5.0.4 on 2025-02-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'product', 'sale_price')},
        ),
    ]
