# Generated by Django 5.0.4 on 2025-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_control_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
