# Generated by Django 5.1.7 on 2025-05-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='unity_price',
            field=models.IntegerField(null=True),
        ),
    ]
