# Generated by Django 5.1.7 on 2025-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_history_total_price_history_unity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
