# Generated by Django 5.0.4 on 2026-01-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_account_role_subscription_notification"),
        ("shops", "0011_history_latitude_history_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Pourcentage"),
                            ("FIXED", "Montant fixe"),
                        ],
                        default="PERCENTAGE",
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="accounts.account",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="shops.sales",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission",
                "verbose_name_plural": "Commissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "status", "-created_at"],
                        name="shops_commi_shop_id_ee7ecc_idx",
                    ),
                    models.Index(
                        fields=["account", "-created_at"],
                        name="shops_commi_account_f2c640_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Loyer"),
                            ("UTILITIES", "Services publics (eau, électricité)"),
                            ("SALARY", "Salaires"),
                            ("TRANSPORT", "Transport"),
                            ("MARKETING", "Marketing/Publicité"),
                            ("MAINTENANCE", "Maintenance/Réparation"),
                            ("SUPPLIES", "Fournitures"),
                            ("OTHER", "Autre"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense_date", models.DateField()),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="expenses/receipts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="accounts.account",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-expense_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "-expense_date"],
                        name="shops_expen_shop_id_92689c_idx",
                    ),
                    models.Index(
                        fields=["expense_type", "-expense_date"],
                        name="shops_expen_expense_3da3c1_idx",
                    ),
                ],
            },
        ),
    ]
