# Generated by Django 5.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0012_commission_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlfrequency",
            name="minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
