# Generated by Django 5.0.4 on 2026-02-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_phone_number"),
        ("shops", "0014_shop_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_password",
            field=models.CharField(
                blank=True,
                help_text="Mot de passe de la boutique, modifiable uniquement par les administrateurs et les agents.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_shops",
                to="accounts.account",
            ),
        ),
    ]
