# Generated by Django 5.0.4 on 2026-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0015_shop_shop_password_alter_shop_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Essai Gratuit"),
                    ("MONTHLY", "Mensuel"),
                    ("6MONTHS", "6 Mois"),
                    ("YEARLY", "Annuel"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="trial_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
