# Generated by Django 5.0.4 on 2026-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0016_shop_subscription_plan_shop_trial_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("FREE", "Essai Gratuit"),
                    ("MONTHLY", "Mensuel"),
                    ("3MONTHS", "3 Mois"),
                    ("6MONTHS", "6 Mois"),
                    ("YEARLY", "Annuel"),
                ],
                default="FREE",
                max_length=20,
            ),
        ),
    ]
