# Generated by Django 5.0.4 on 2026-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0017_alter_shop_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="buy_price",
            field=models.FloatField(
                default=0.0,
                help_text="Prix d'achat unitaire au moment de la vente pour le calcul du bénéfice",
            ),
        ),
    ]
