# Generated by Django 5.0.4 on 2026-03-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0018_sales_buy_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="shop",
            name="payment_mode_active",
            field=models.BooleanField(
                default=True,
                help_text="Active ou désactive le mode de paiement pour cette boutique.",
            ),
        ),
    ]
