# Generated by Django 5.0.4 on 2026-01-29 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_account_role_subscription_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent ou admin qui a créé cet utilisateur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
